#
# This file will be included by cmake/share/Files.cmake
#
# cmake/reflect/_Libraries.cmake is generated by
# `mulle-sourcetree-to-cmake` via `mulle-sde reflect`.
# Edits will be lost.
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_LIBRARIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# there are no libraries in the sourcetree
