### If you want to edit this, copy it from cmake/share to cmake. It will be
### picked up in preference over the one in cmake/share. And it will not get
### clobbered with the next upgrade.

# can be included multiple times is shared by Library.cmake and Framework.cmake

if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# Frameworks aren't forced
CreateForceAllLoadList( ALL_LOAD_DEPENDENCY_LIBRARIES FORCE_ALL_LOAD_DEPENDENCY_LIBRARIES)
#CreateForceAllLoadList( ALL_LOAD_DEPENDENCY_FRAMEWORKS FORCE_ALL_LOAD_DEPENDENCY_FRAMEWORKS)
CreateForceAllLoadList( ALL_LOAD_OPTIONAL_DEPENDENCY_LIBRARIES FORCE_ALL_LOAD_OPTIONAL_DEPENDENCY_LIBRARIES)
#CreateForceAllLoadList( ALL_LOAD_OPTIONAL_DEPENDENCY_FRAMEWORKS FORCE_ALL_LOAD_OPTIONAL_DEPENDENCY_FRAMEWORKS)
CreateForceAllLoadList( ALL_LOAD_OS_SPECIFIC_LIBRARIES FORCE_ALL_LOAD_OS_SPECIFIC_LIBRARIES)
#CreateForceAllLoadList( ALL_LOAD_OS_SPECIFIC_FRAMEWORKS FORCE_ALL_LOAD_OS_SPECIFIC_FRAMEWORKS)
# 
# message( STATUS "DEPENDENCY_LIBRARIES=${DEPENDENCY_LIBRARIES}")
# message( STATUS "DEPENDENCY_FRAMEWORKS=${DEPENDENCY_FRAMEWORKS}")
# message( STATUS "OPTIONAL_DEPENDENCY_LIBRARIES=${OPTIONAL_DEPENDENCY_LIBRARIES}")
# message( STATUS "OPTIONAL_DEPENDENCY_FRAMEWORKS=${OPTIONAL_DEPENDENCY_FRAMEWORKS}")
# message( STATUS "OS_SPECIFIC_LIBRARIES=${OS_SPECIFIC_LIBRARIES}")
# message( STATUS "OS_SPECIFIC_FRAMEWORKS=${OS_SPECIFIC_FRAMEWORKS}")
# 
# message( STATUS "SHARED_LIBRARY_LIST=${SHARED_LIBRARY_LIST}")
# message( STATUS "FORCE_ALL_LOAD_DEPENDENCY_LIBRARIES=${FORCE_ALL_LOAD_DEPENDENCY_LIBRARIES}")
# message( STATUS "ALL_LOAD_DEPENDENCY_FRAMEWORKS=${ALL_LOAD_DEPENDENCY_FRAMEWORKS}")
# message( STATUS "FORCE_ALL_LOAD_OPTIONAL_DEPENDENCY_LIBRARIES=${FORCE_ALL_LOAD_OPTIONAL_DEPENDENCY_LIBRARIES}")
# message( STATUS "ALL_LOAD_OPTIONAL_DEPENDENCY_FRAMEWORKS=${ALL_LOAD_OPTIONAL_DEPENDENCY_FRAMEWORKS}")
# message( STATUS "FORCE_ALL_LOAD_OS_SPECIFIC_LIBRARIES=${FORCE_ALL_LOAD_OS_SPECIFIC_LIBRARIES}")
# message( STATUS "ALL_LOAD_OS_SPECIFIC_FRAMEWORKS=${ALL_LOAD_OS_SPECIFIC_FRAMEWORKS}")

set( SHARED_LIBRARY_LIST
   ${FORCE_ALL_LOAD_DEPENDENCY_LIBRARIES}
   ${ALL_LOAD_DEPENDENCY_FRAMEWORKS}
   ${FORCE_ALL_LOAD_OPTIONAL_DEPENDENCY_LIBRARIES}
   ${ALL_LOAD_OPTIONAL_DEPENDENCY_FRAMEWORKS}
   ${FORCE_ALL_LOAD_OS_SPECIFIC_LIBRARIES}
   ${ALL_LOAD_OS_SPECIFIC_FRAMEWORKS}
   ${SHARED_LIBRARY_LIST}
)

include( PostSharedLibraryAuxC OPTIONAL)
