/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_objc_runtime_versioncheck_h__
#define mulle_objc_runtime_versioncheck_h__

#if defined( MULLE__CORE_VERSION)
# ifndef MULLE__CORE_VERSION_MIN
#  define MULLE__CORE_VERSION_MIN  ((0UL << 20) | (6 << 8) | 0)
# endif
# ifndef MULLE__CORE_VERSION_MAX
#  define MULLE__CORE_VERSION_MAX  ((0UL << 20) | (7 << 8) | 0)
# endif
# if MULLE__CORE_VERSION < MULLE__CORE_VERSION_MIN || MULLE__CORE_VERSION >= MULLE__CORE_VERSION_MAX
#  pragma message("MULLE__CORE_VERSION     is " MULLE_C_STRINGIFY_MACRO( MULLE__CORE_VERSION))
#  pragma message("MULLE__CORE_VERSION_MIN is " MULLE_C_STRINGIFY_MACRO( MULLE__CORE_VERSION_MIN))
#  pragma message("MULLE__CORE_VERSION_MAX is " MULLE_C_STRINGIFY_MACRO( MULLE__CORE_VERSION_MAX))
#  if MULLE__CORE_VERSION < MULLE__CORE_VERSION_MIN
#   error "mulle-core is too old"
#  else
#   error "mulle-core is too new"
#  endif
# endif
#endif

#endif
