/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_runtime_include_h__
#define _mulle_objc_runtime_include_h__

// You can tweak the following #include with these commands.
// (Use 8066A0F0-88B4-4E1F-AC6D-3EF08A277B4E instead of mulle-core if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-core no-header`
//    rename:              `mulle-sde dependency|library set mulle-core include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-core <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-core [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-core [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-core [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-core no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-core/mulle-core.h>   // mulle-core

#endif
