/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_runtime_include_private_h__
#define _mulle_objc_runtime_include_private_h__

// You can tweak the following #include with these commands.
// (Use A80369B3-6A83-4563-83C7-F590C5967E84 instead of mulle-stacktrace if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-stacktrace no-header`
//    rename:             `mulle-sde dependency|library set mulle-stacktrace include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-stacktrace <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-stacktrace [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-stacktrace [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-stacktrace [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-stacktrace no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-stacktrace/mulle-stacktrace.h>   // mulle-stacktrace

// You can tweak the following #include with these commands.
// (Use E0364339-E5A0-45C1-AFC7-87896F3FAA2A instead of mulle-atinit if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-atinit no-header`
//    rename:             `mulle-sde dependency|library set mulle-atinit include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-atinit <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-atinit [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-atinit [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-atinit [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-atinit no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-atinit/mulle-atinit.h>   // mulle-atinit

// You can tweak the following #include with these commands.
// (Use 9956BD7E-D6ED-44BC-B864-B2BAC12846D3 instead of mulle-atexit if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-atexit no-header`
//    rename:             `mulle-sde dependency|library set mulle-atexit include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-atexit <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-atexit [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-atexit [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-atexit [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-atexit no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-atexit/mulle-atexit.h>   // mulle-atexit

// You can tweak the following #include with these commands.
// (Use E67C3C5D-5B47-490D-B4FB-00C98540F287 instead of mulle-dlfcn if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-dlfcn no-header`
//    rename:             `mulle-sde dependency|library set mulle-dlfcn include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-dlfcn <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-dlfcn [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-dlfcn [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-dlfcn [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-dlfcn no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-dlfcn/mulle-dlfcn.h>   // mulle-dlfcn

#endif
