/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_objc_runtime_versioncheck_h__
#define mulle_objc_runtime_versioncheck_h__

#if defined( MULLE__ATEXIT_VERSION)
# ifndef MULLE__ATEXIT_VERSION_MIN
#  define MULLE__ATEXIT_VERSION_MIN  ((0 << 20) | (0 << 8) | 14)
# endif
# ifndef MULLE__ATEXIT_VERSION_MAX
#  define MULLE__ATEXIT_VERSION_MAX  ((0 << 20) | (1 << 8) | 0)
# endif
# if MULLE__ATEXIT_VERSION < MULLE__ATEXIT_VERSION_MIN
#  error "mulle-atexit is too old"
# endif
# if MULLE__ATEXIT_VERSION >= MULLE__ATEXIT_VERSION_MAX
#  error "mulle-atexit is too new"
# endif
#endif

#if defined( MULLE__ATINIT_VERSION)
# ifndef MULLE__ATINIT_VERSION_MIN
#  define MULLE__ATINIT_VERSION_MIN  ((0 << 20) | (0 << 8) | 11)
# endif
# ifndef MULLE__ATINIT_VERSION_MAX
#  define MULLE__ATINIT_VERSION_MAX  ((0 << 20) | (1 << 8) | 0)
# endif
# if MULLE__ATINIT_VERSION < MULLE__ATINIT_VERSION_MIN
#  error "mulle-atinit is too old"
# endif
# if MULLE__ATINIT_VERSION >= MULLE__ATINIT_VERSION_MAX
#  error "mulle-atinit is too new"
# endif
#endif

#endif
