/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE NONE|DISABLE.
*/
#ifndef _mulle_objc_runtime_include_private_h__
#define _mulle_objc_runtime_include_private_h__

# include <mulle-stacktrace/mulle-stacktrace.h>   // mulle-stacktrace

#endif
