/*
*   This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_INCLUDE_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_runtime_include_h__
#define _mulle_objc_runtime_include_h__

# include <mulle-concurrent/mulle-concurrent.h>   // mulle-concurrent

# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

# include <mulle-testallocator/mulle-testallocator.h>   // mulle-testallocator

#endif
