/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_runtime_include_h__
#define _mulle_objc_runtime_include_h__

// remove with `mulle-sourcetree mark mulle-concurrent no-header`
// rename with `mulle-sourcetree mark mulle-concurrent set include whatever.h`
# include <mulle-concurrent/mulle-concurrent.h>   // mulle-concurrent

// remove with `mulle-sourcetree mark mulle-vararg no-header`
// rename with `mulle-sourcetree mark mulle-vararg set include whatever.h`
# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

// remove with `mulle-sourcetree mark mulle-atinit no-header`
// rename with `mulle-sourcetree mark mulle-atinit set include whatever.h`
# include <mulle-atinit/mulle-atinit.h>   // mulle-atinit

// remove with `mulle-sourcetree mark mulle-atexit no-header`
// rename with `mulle-sourcetree mark mulle-atexit set include whatever.h`
# include <mulle-atexit/mulle-atexit.h>   // mulle-atexit

#endif
