/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_runtime_include_private_h__
#define _mulle_objc_runtime_include_private_h__

/* no headers */

#endif
