/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_runtime__dependencies_h__
#define _mulle_objc_runtime__dependencies_h__

# include <mulle-concurrent/mulle-concurrent.h>   // mulle-concurrent

# include <mulle-vararg/mulle-vararg.h>   // mulle-vararg

#endif
