#ifndef _mulle_objc_runtime_dependencies_h__
#define _mulle_objc_runtime_dependencies_h__

/* a central include file to keep dependencies out of the actual .c files
   the advantage: .c files can be moved to other projects and don't need
   to be edited. Also less typing...
*/

/* include header file automatically generated by mulle-c-sourcetree-update */
# include "_mulle-objc-runtime-dependencies.h"

/* add some more dependencies here */
#include <mulle-test-allocator/mulle-test-allocator.h>

#endif
