#ifndef MULLE_OBJC_ALLOC_METHODID

#define MULLE_OBJC_ALLOC_METHODID                MULLE_OBJC_METHODID( 0xab1bb16b) // "alloc"
#define MULLE_OBJC_AUTORELEASE_METHODID          MULLE_OBJC_METHODID( 0x8c9fa1fc) // "autorelease"
#define MULLE_OBJC_CLASS_METHODID                MULLE_OBJC_METHODID( 0xb3e0bffa) // "class"
#define MULLE_OBJC_COPY_METHODID                 MULLE_OBJC_METHODID( 0x562ea44e) // "copy"
#define MULLE_OBJC_DEALLOC_METHODID              MULLE_OBJC_METHODID( 0x9929eb3d) // "dealloc"
#define MULLE_OBJC_DEINITIALIZE_METHODID         MULLE_OBJC_METHODID( 0x62098d89) // "deinitialize"
#define MULLE_OBJC_DEPENDENCIES_METHODID         MULLE_OBJC_METHODID( 0x53d9d606) // "dependencies"
#define MULLE_OBJC_FINALIZE_METHODID             MULLE_OBJC_METHODID( 0x9de99ffa) // "finalize"
#define MULLE_OBJC_FORWARD_METHODID              MULLE_OBJC_METHODID( 0x295aa601) // "forward:"
#define MULLE_OBJC_INITIALIZE_METHODID           MULLE_OBJC_METHODID( 0xe92964bc) // "initialize"
#define MULLE_OBJC_INIT_METHODID                 MULLE_OBJC_METHODID( 0x6b1d3731) // "init"
#define MULLE_OBJC_INSTANTIATE_METHODID          MULLE_OBJC_METHODID( 0x51e64db8) // "instantiate"
#define MULLE_OBJC_LOAD_METHODID                 MULLE_OBJC_METHODID( 0x60759e9e) // "load"
#define MULLE_OBJC_MUTABLECOPY_METHODID          MULLE_OBJC_METHODID( 0xa1eb570f) // "mutableCopy"
#define MULLE_OBJC_INSTANCE_METHODID             MULLE_OBJC_METHODID( 0xb86d9920) // "instance"
#define MULLE_OBJC_RELEASE_METHODID              MULLE_OBJC_METHODID( 0x036ae7e1) // "release"
#define MULLE_OBJC_RETAIN_METHODID               MULLE_OBJC_METHODID( 0x8bcc57c8) // "retain"
#define MULLE_OBJC_RETAINCOUNT_METHODID          MULLE_OBJC_METHODID( 0x67a90e37) // "retainCount"
#define MULLE_OBJC_UNLOAD_METHODID               MULLE_OBJC_METHODID( 0xb6a58d22) // "unload"
#define MULLE_OBJC_GENERIC_GETTER_METHODID       MULLE_OBJC_METHODID( 0xf0cb86d3) // ":"
#define MULLE_OBJC_WILLFINALIZE_METHODID         MULLE_OBJC_METHODID( 0x70bd9f78) // "willFinalize"

#define MULLE_OBJC_ADDOBJECT_METHODID            MULLE_OBJC_METHODID( 0xfead2dba) // "addObject:"
#define MULLE_OBJC_REMOVEOBJECT_METHODID         MULLE_OBJC_METHODID( 0x7b167f8c) // "removeObject:"
#define MULLE_OBJC_WILLCHANGE_METHODID           MULLE_OBJC_METHODID( 0x82bfc654) // "willChange"
#define MULLE_OBJC_WILLREADRELATIONSHIP_METHODID MULLE_OBJC_METHODID( 0x472007bc) // "willReadRelationship:"

#define MULLE_OBJC_MULLE_ALLOCATOR_METHODID      MULLE_OBJC_METHODID( 0x6b8b61fc) // "mulleAllocator"

// used for boring trace
#define MULLE_OBJC_MULLE_COUNT_OBJECT_METHODID   MULLE_OBJC_METHODID( 0xf1cb600c) // "mulleCountObject:"

#endif
