# cmake/_Sources.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( DEBUG_SOURCES
src/debug/mulle-objc-csvdump.c
src/debug/mulle-objc-dotdump.c
src/debug/mulle-objc-html.c
src/debug/mulle-objc-htmldump.c
src/debug/mulle-objc-lldb.c
)

set( SOURCES
src/mulle-objc-cache.c
src/mulle-objc-call.c
src/mulle-objc-callqueue.c
src/mulle-objc-class.c
src/mulle-objc-classpair.c
src/mulle-objc-class-search.c
src/mulle-objc-fastenumeration.c
src/mulle-objc-fastmethodtable.c
src/mulle-objc-fnv1a.c
src/mulle-objc-fnv1.c
src/mulle-objc-infraclass.c
src/mulle-objc-ivar.c
src/mulle-objc-ivarlist.c
src/mulle-objc-kvccache.c
src/mulle-objc-load.c
src/mulle-objc-metaclass.c
src/mulle-objc-method.c
src/mulle-objc-methodlist.c
src/mulle-objc-property.c
src/mulle-objc-propertylist.c
src/mulle-objc-protocol.c
src/mulle-objc-protocollist.c
src/mulle-objc-retain-release.c
src/mulle-objc-signature.c
src/mulle-objc-super.c
src/mulle-objc-try-catch-finally.c
src/mulle-objc-uniqueidarray.c
src/mulle-objc-uniqueid.c
src/mulle-objc-universe.c
src/mulle-objc-universe-class.c
src/mulle-objc-universe-global.c
)

set( STANDALONE_SOURCES
src/mulle-objc-runtime-standalone.c
)

set( STARTUP_SOURCES
src/mulle-objc-runtime-startup.c
)

set( UNIQUEID_SOURCES
src/mulle-objc-uniqueid/main.c
)
